<a href="https://colab.research.google.com/github/imiled/DeepLearningMaster/blob/master/Tensorflow_Utils.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!apt-get update > /dev/null 2>&1
!apt-get install cmake > /dev/null 2>&1
!pip install --upgrade setuptools > /dev/null 2>&1
!pip install tensorflow-gpu==2.0.0 > /dev/null 2>&1

In [0]:
import tensorflow as tf
import numpy as np

Let's try to fit a parabollic function using 
 

In [0]:
f = lambda x: 2*x**2 + x +1
x_train = np.linspace(-100,100,1000)
y_train = f(x_train)

x_test = np.linspace(-110,-100.01,10)
y_test = f(x_test)

# Model Definition

### Sequential API

In [0]:
sequential_model = tf.keras.models.Sequential()
sequential_model.add(tf.keras.layers.Dense(64, input_shape=(1,), activation='relu'))
sequential_model.add(tf.keras.layers.Dense(32, activation='relu'))
sequential_model.add(tf.keras.layers.Dense(1))

In [22]:
sequential_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 64)                128       
_________________________________________________________________
dense_7 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 33        
Total params: 2,241
Trainable params: 2,241
Non-trainable params: 0
_________________________________________________________________


In [33]:
sequential_model.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.mean_squared_error)
sequential_model.fit(x_train, y_train, batch_size=8, epochs=10, validation_split=.2)
sequential_model.predict(x_test)

Train on 800 samples, validate on 200 samples
Epoch 1/10
800/800 [==============================] - 1s 673us/sample - loss: 51219951.4150 - val_loss: 179967421.1200
Epoch 2/10
800/800 [==============================] - 0s 265us/sample - loss: 44510819.3400 - val_loss: 162786089.7600
Epoch 3/10
800/800 [==============================] - 0s 262us/sample - loss: 30260426.7675 - val_loss: 128555415.8400
Epoch 4/10
800/800 [==============================] - 0s 274us/sample - loss: 13854141.1150 - val_loss: 87440030.4800
Epoch 5/10
800/800 [==============================] - 0s 270us/sample - loss: 5331467.3341 - val_loss: 59075870.3200
Epoch 6/10
800/800 [==============================] - 0s 275us/sample - loss: 3645309.5881 - val_loss: 48327514.1200
Epoch 7/10
800/800 [==============================] - 0s 248us/sample - loss: 3516865.6900 - val_loss: 44380955.3000
Epoch 8/10
800/800 [==============================] - 0s 260us/sample - loss: 3497689.0112 - val_loss: 43324918.3200
Epoch 9/10


array([[16241.183],
       [16077.847],
       [15914.514],
       [15751.178],
       [15587.843],
       [15424.508],
       [15261.173],
       [15097.841],
       [14934.505],
       [14771.172]], dtype=float32)

### Functional API

In [24]:
x = tf.keras.layers.Input(shape=(1,))
dense_relu_64 = tf.keras.layers.Dense(64, activation='relu')(x)
dense_relu_32 = tf.keras.layers.Dense(32, activation='relu')(dense_relu_64)
y = tf.keras.layers.Dense(1)(dense_relu_32)

functional_model = tf.keras.Model(x, y)
functional_model.summary()


Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
dense_9 (Dense)              (None, 64)                128       
_________________________________________________________________
dense_10 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 33        
Total params: 2,241
Trainable params: 2,241
Non-trainable params: 0
_________________________________________________________________


In [34]:
functional_model.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.mean_squared_error)
functional_model.fit(x_train, y_train, batch_size=8, epochs=10, validation_split=.2)
functional_model.predict(x_test)

Train on 800 samples, validate on 200 samples
Epoch 1/10
800/800 [==============================] - 1s 855us/sample - loss: 52316241.7650 - val_loss: 177750091.0400
Epoch 2/10
800/800 [==============================] - 0s 260us/sample - loss: 48050091.2750 - val_loss: 154102114.7200
Epoch 3/10
800/800 [==============================] - 0s 267us/sample - loss: 37417163.9475 - val_loss: 111928867.9200
Epoch 4/10
800/800 [==============================] - 0s 260us/sample - loss: 22088941.4500 - val_loss: 66693018.4800
Epoch 5/10
800/800 [==============================] - 0s 257us/sample - loss: 9640977.3887 - val_loss: 45651136.9000
Epoch 6/10
800/800 [==============================] - 0s 268us/sample - loss: 4492526.4212 - val_loss: 40633567.9800
Epoch 7/10
800/800 [==============================] - 0s 253us/sample - loss: 3594883.0553 - val_loss: 42505948.9800
Epoch 8/10
800/800 [==============================] - 0s 251us/sample - loss: 3514353.5312 - val_loss: 41607011.8200
Epoch 9/10


array([[16260.148],
       [16096.837],
       [15933.527],
       [15770.219],
       [15606.906],
       [15443.598],
       [15280.286],
       [15116.979],
       [14953.667],
       [14790.358]], dtype=float32)

### Model Subclassing

In [0]:
class NN(tf.keras.Model):

    def __init__(self):
        super(NN, self).__init__()
        self.dense_relu_64 = tf.keras.layers.Dense(64, activation='relu')
        self.dense_relu_32 = tf.keras.layers.Dense(32, activation='relu')
        self.dense_linear_1 = tf.keras.layers.Dense(1)

    def call(self, inputs):
        x = self.dense_relu_64(inputs)
        x = self.dense_relu_32(x)
        x = self.dense_linear_1(x)
        return x

In [27]:
subclassing = NN()
x_test_sub = np.expand_dims(x_test, axis=1)
print(subclassing(x_test_sub))


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

tf.Tensor(
[[-11.257616 ]
 [-11.144018 ]
 [-11.0304165]
 [-10.916816 ]
 [-10.803221 ]
 [-10.689617 ]
 [-10.576019 ]
 [-10.462423 ]
 [-10.348821 ]
 [-10.235218 ]], shape=(10, 1), dtype=float32)


In [28]:
x_test.shape

(10,)

# Training Model Subclassing

### Fit

In [35]:
subclassing.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.mean_squared_error)
subclassing.fit(x_train, y_train, batch_size=8, epochs=10, validation_split=.2)
subclassing.predict(x_test)

Train on 800 samples, validate on 200 samples
Epoch 1/10
800/800 [==============================] - 1s 678us/sample - loss: 52609312.4250 - val_loss: 178828661.1200
Epoch 2/10
800/800 [==============================] - 0s 261us/sample - loss: 48022279.3050 - val_loss: 149698877.9200
Epoch 3/10
800/800 [==============================] - 0s 266us/sample - loss: 36090701.1013 - val_loss: 94543868.6400
Epoch 4/10
800/800 [==============================] - 0s 258us/sample - loss: 19646798.1569 - val_loss: 52639700.3800
Epoch 5/10
800/800 [==============================] - 0s 274us/sample - loss: 8065875.4094 - val_loss: 40818413.5700
Epoch 6/10
800/800 [==============================] - 0s 266us/sample - loss: 4098950.7325 - val_loss: 41741364.6800
Epoch 7/10
800/800 [==============================] - 0s 261us/sample - loss: 3545799.0925 - val_loss: 42927907.0700
Epoch 8/10
800/800 [==============================] - 0s 255us/sample - loss: 3502913.4066 - val_loss: 42381495.8800
Epoch 9/10
8

array([[16193.671],
       [16030.961],
       [15868.251],
       [15705.54 ],
       [15542.829],
       [15380.118],
       [15217.409],
       [15054.699],
       [14891.986],
       [14729.276]], dtype=float32)

### tf.GradientTape

In [0]:
def optimize(model, x, y):
    with tf.GradientTape() as tape: # save the cpst function
        pred = model(x)
        loss = tf.reduce_mean(tf.keras.losses.MSE(pred, y))

    grads = tape.gradient(loss, model.trainable_weights)
    optimizer = tf.keras.optimizers.Adam()
    optimizer.apply_gradients(zip(grads, model.trainable_weights)) 
    return model, loss

In [32]:
subclassing = NN()
x_test_sub = np.expand_dims(x_test, axis=1)
epochs = 10
for i in range(epochs):
    subclassing, loss =  optimize(subclassing, x_test_sub, y_test)
    print(i, loss) 


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

0 tf.Tensor(484241421.1634984, shape=(), dtype=float64)
1 tf.Tensor(484148922.7991501, shape=(), dtype=float64)
2 tf.Tensor(484062814.16717607, shape=(), dtype=float64)
3 tf.Tensor(483976370.272464, shape=(), dtype=float64)
4 tf.Tensor(483889630.78544986, shape=(), dtype=float64)
5 tf.Tensor(483802841.0850207, shape=(), dtype=float64)
6 tf.Tensor(483715397.6963617, shape=(), dtype=float64)
7 tf.Tensor(483627617.66092634, shape=(), dtype=float64)
8 tf.Tensor(483539500.72130126, shape=(), dtype=float64)
9